// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamBuilder.Infrastructure.Data;

#nullable disable

namespace TeamBuilder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TeamBuilderDbContext))]
    partial class TeamBuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentParticipantCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDetached")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OccurrenceIndex")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("ScheduledEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("HostId");

                    b.HasIndex("Region");

                    b.HasIndex("ScheduledStartUtc");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeriesId", "ScheduledStartUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_Events_SeriesId_ScheduledStartUtc")
                        .HasFilter("[SeriesId] IS NOT NULL");

                    b.HasIndex("VenueId", "Status", "ScheduledStartUtc")
                        .HasDatabaseName("IX_Events_VenueId_Status_ScheduledStartUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("VenueId", "Status", "ScheduledStartUtc"), new[] { "Category" });

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("MaterializedThroughLocalDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("SeriesEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SeriesStartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("VenueId");

                    b.ToTable("EventSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventSeries_DurationMinutes_Range", "[DurationMinutes] > 0 AND [DurationMinutes] <= 10080");

                            t.HasCheckConstraint("CK_EventSeries_MaxParticipants_Range", "[MaxParticipants] >= 1 AND [MaxParticipants] <= 100000");
                        });
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_JoinRequests_TeamId_PlayerId_Pending")
                        .HasFilter("[Status] = 1");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Email");

                    b.HasIndex("Region");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.PlayerIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("UX_PlayerIdentities_Issuer_Subject");

                    b.ToTable("PlayerIdentities");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExitReason")
                        .HasColumnType("int");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceRoleLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("OccurrenceId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_RosterAssignments_OccurrenceId_PlayerId_Supply")
                        .HasFilter("[Status] IN (1, 2, 3, 4)");

                    b.HasIndex("OccurrenceId", "Status");

                    b.HasIndex("ReplacedAssignmentId", "OccurrenceId");

                    b.HasIndex("RequirementId", "OccurrenceId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RequirementId", "OccurrenceId"), new[] { "Status" });

                    b.ToTable("RosterAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_RosterAssignments_ExitReason_Range", "[ExitReason] IS NULL OR ([ExitReason] >= 1 AND [ExitReason] <= 5)");

                            t.HasCheckConstraint("CK_RosterAssignments_ReplacedAssignmentId_NotSelf", "[ReplacedAssignmentId] IS NULL OR [ReplacedAssignmentId] <> [Id]");

                            t.HasCheckConstraint("CK_RosterAssignments_Source_Range", "[Source] >= 1 AND [Source] <= 4");

                            t.HasCheckConstraint("CK_RosterAssignments_Status_Range", "[Status] >= 1 AND [Status] <= 7");
                        });
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsConfirmed");

                    b.HasIndex("PlayerId");

                    b.HasIndex("EventId", "PlayerId");

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImportedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsProcessed");

                    b.ToTable("RosterImports");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceRoleLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId", "RoleCode")
                        .IsUnique()
                        .HasDatabaseName("UX_RosterRequirements_OccurrenceId_RoleCode");

                    b.ToTable("RosterRequirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_RosterRequirements_RequiredCount_Range", "[RequiredCount] >= 1 AND [RequiredCount] <= 100000");

                            t.HasCheckConstraint("CK_RosterRequirements_RoleCode_NotEmpty", "[RoleCode] <> N''");
                        });
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentMemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsAcceptingMembers")
                        .HasColumnType("bit");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("int");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Region");

                    b.HasIndex("LifecycleStatus", "IsAcceptingMembers");

                    b.ToTable("Teams", t =>
                        {
                            t.HasCheckConstraint("CK_Teams_CurrentMemberCount_Bounds", "[CurrentMemberCount] >= 0 AND [CurrentMemberCount] <= [MaxMembers]");
                        });
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "IsActive")
                        .HasDatabaseName("IX_TeamMembers_PlayerId_IsActive");

                    b.HasIndex("TeamId", "IsActive")
                        .HasDatabaseName("IX_TeamMembers_TeamId_IsActive");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_TeamMembers_TeamId_PlayerId")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlayerId");

                    b.ToTable("Venues", t =>
                        {
                            t.HasCheckConstraint("CK_Venues_Latitude_Range", "[Latitude] >= -90 AND [Latitude] <= 90");

                            t.HasCheckConstraint("CK_Venues_Longitude_Range", "[Longitude] >= -180 AND [Longitude] <= 180");

                            t.HasCheckConstraint("CK_Venues_PrivacyLevel_Range", "[PrivacyLevel] >= 1 AND [PrivacyLevel] <= 2");
                        });
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventOccurrence", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Host")
                        .WithMany("HostedEvents")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamBuilder.Domain.Entities.EventSeries", "Series")
                        .WithMany("Occurrences")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamBuilder.Domain.Entities.Team", "Team")
                        .WithMany("Events")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamBuilder.Domain.Entities.Venue", "Venue")
                        .WithMany("Occurrences")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Host");

                    b.Navigation("Series");

                    b.Navigation("Team");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventSeries", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamBuilder.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamBuilder.Domain.Entities.Venue", "Venue")
                        .WithMany("EventSeries")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Host");

                    b.Navigation("Team");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Player")
                        .WithMany("JoinRequests")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamBuilder.Domain.Entities.Team", "Team")
                        .WithMany("JoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.PlayerIdentity", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Player")
                        .WithMany("Identities")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterAssignment", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.EventOccurrence", "EventOccurrence")
                        .WithMany("RosterAssignments")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RosterAssignments_Events_OccurrenceId");

                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Player")
                        .WithMany("RosterAssignments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RosterAssignments_Players_PlayerId");

                    b.HasOne("TeamBuilder.Domain.Entities.RosterAssignment", "ReplacedAssignment")
                        .WithMany()
                        .HasForeignKey("ReplacedAssignmentId", "OccurrenceId")
                        .HasPrincipalKey("Id", "OccurrenceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RosterAssignments_RosterAssignments_ReplacedAssignmentId_OccurrenceId");

                    b.HasOne("TeamBuilder.Domain.Entities.RosterRequirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId", "OccurrenceId")
                        .HasPrincipalKey("Id", "OccurrenceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RosterAssignments_RosterRequirements_RequirementId_OccurrenceId");

                    b.Navigation("EventOccurrence");

                    b.Navigation("Player");

                    b.Navigation("ReplacedAssignment");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterEntry", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.EventOccurrence", "Event")
                        .WithMany("RosterEntries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Player")
                        .WithMany("RosterEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.RosterRequirement", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.EventOccurrence", "EventOccurrence")
                        .WithMany("RosterRequirements")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventOccurrence");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Team", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Owner")
                        .WithMany("OwnedTeams")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "Player")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamBuilder.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Venue", b =>
                {
                    b.HasOne("TeamBuilder.Domain.Entities.Player", "CreatedByPlayer")
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByPlayer");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventOccurrence", b =>
                {
                    b.Navigation("RosterAssignments");

                    b.Navigation("RosterEntries");

                    b.Navigation("RosterRequirements");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.EventSeries", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Player", b =>
                {
                    b.Navigation("HostedEvents");

                    b.Navigation("Identities");

                    b.Navigation("JoinRequests");

                    b.Navigation("OwnedTeams");

                    b.Navigation("RosterAssignments");

                    b.Navigation("RosterEntries");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Team", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TeamBuilder.Domain.Entities.Venue", b =>
                {
                    b.Navigation("EventSeries");

                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
